//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usermaster
    {
        public long ID { get; set; }
        public string Username { get; set; }
        public string EmailID { get; set; }
        public string Password { get; set; }
        public Nullable<long> UserRoleID { get; set; }
        public string MobileNo { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public Nullable<long> Country { get; set; }
        public Nullable<long> State { get; set; }
        public Nullable<long> City { get; set; }
        public string Pincode { get; set; }
        public bool IsActive { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual CityMaster CityMaster { get; set; }
        public virtual CoutryMaster CoutryMaster { get; set; }
        public virtual StateMaster StateMaster { get; set; }
    }
}
